version: '3'

services:
  db:
    container_name: ez_notes_mysql
    image: mysql:latest
    restart: always
    ports:
      - "5001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ez_notes_dev_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: ez_notes_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ez_notes_dev_password
      UPLOAD_LIMIT: 50M